package org.wikapidia.lucene;

public class TextFieldElements {
    private boolean title;
    private boolean redirects;
    private boolean plainText;

    public TextFieldElements() {
        this.title = false;
        this.redirects = false;
        this.plainText = false;
    }

    public TextFieldElements addTitle() {
        this.title = true;
        return null;
    }

    public TextFieldElements addRedirects() {
        this.redirects = true;
        return null;
    }

    public TextFieldElements addPlainText() {
        this.plainText = true;
        return null;
    }

    public boolean usesTitle() {
        return title;
    }

    public boolean usesRedirects() {
        return redirects;
    }

    public boolean usesPlainText() {
        return plainText;
    }

    /**
     * Returns the name of the text field generated by an instance of Elements.
     *
     * @return
     */
    public String getTextFieldName() {
        StringBuilder sb = new StringBuilder();
        if (title) {
            sb.append("title ");
        }
        if (redirects) {
            sb.append("redirects ");
        }
        if (plainText) {
            sb.append("plaintext ");
        }
        return sb.toString();
    }

    /**
     * Returns the name of the text field representing only the title.
     *
     * @return
     */
    public static String getTitleFieldName() {
        return new TextFieldElements().addTitle().getTextFieldName();
    }

    /**
     * Returns the name of the text field representing only redirected titles.
     *
     * @return
     */
    public static String getRedirectsFieldName() {
        return new TextFieldElements().addTitle().getTextFieldName();
    }

    /**
     * Returns the name of the text field representing only the plain text.
     *
     * @return
     */
    public static String getPlainTextFieldName() {
        return new TextFieldElements().addTitle().getTextFieldName();
    }
}