CREATE INDEX IF NOT EXISTS WD_LABELS_IDX ON WIKIDATA_ITEM_LABELS(ITEM_ID, LANG_ID);
CREATE INDEX IF NOT EXISTS WD_DESC_IDX ON WIKIDATA_ITEM_DESCRIPTIONS(ITEM_ID, LANG_ID);
CREATE INDEX IF NOT EXISTS WD_ALIAS_IDX ON WIKIDATA_ITEM_ALIASES(ITEM_ID, LANG_ID);
CREATE INDEX IF NOT EXISTS WD_STATEMENT_ITEM_IDX ON WIKIDATA_STATEMENT(ITEM_ID);
CREATE INDEX IF NOT EXISTS WD_STATEMENT_PROP_IDX ON WIKIDATA_STATEMENT(PROP_ID);
