package org.wikapidia.mapper;

import org.wikapidia.conf.ConfigurationException;
import org.wikapidia.conf.Configurator;
import org.wikapidia.core.dao.DaoException;
import org.wikapidia.core.lang.LanguageSet;
import org.wikapidia.core.model.UniversalPage;

import java.util.Iterator;

/**
 */
public abstract class ConceptMapper {

    /**
     * Algorithm IDs for the various concept parsing algorithms
     */
    public static final int MONOLINGUAL_ALGORITHM_ID = 0;
    public static final int CONCEPTUALIGN_ALGORITHM_ID = 1;

    protected final Configurator configurator;

    protected ConceptMapper(Configurator configurator) {
        this.configurator = configurator;
    }

    /**
     * Returns an Iterator of UniversalPages generated by the concept mapping algorithm
     * @param ls the language set to map
     * @return an Iterator of universal pages
     * @throws DaoException
     * @throws ConfigurationException
     */
    public abstract Iterator<UniversalPage> getConceptMap(LanguageSet ls) throws DaoException, ConfigurationException;

}
