package org.wikapidia.mapper;

import org.wikapidia.conf.ConfigurationException;
import org.wikapidia.core.WikapidiaException;
import org.wikapidia.core.dao.DaoException;
import org.wikapidia.core.dao.LocalLinkDao;
import org.wikapidia.core.dao.LocalPageDao;
import org.wikapidia.core.lang.LanguageSet;
import org.wikapidia.core.model.LocalPage;
import org.wikapidia.core.model.UniversalLink;
import org.wikapidia.core.model.UniversalPage;

import java.util.Iterator;

/**
 *
 * @author Ari Weiland
 *
 * An abstract superclass that lays the framework for a concept mapping algorithm.
 *
 */
public abstract class ConceptMapper {

    private final int id;

    protected final LocalPageDao<LocalPage> localPageDao;

    /**
     * All purpose constructor
     * @param id
     * @param localPageDao
     */
    public ConceptMapper(int id, LocalPageDao<LocalPage> localPageDao) {
        this.localPageDao = localPageDao;
        this.id = id;
    }

    public int getId() {
        return id;
    }

    /**
     * Returns an Iterator of UniversalPages generated by the concept mapping algorithm.
     * Requires a database of LocalPages.
     * @param ls the language set to map
     * @return an Iterator of universal pages
     * @throws DaoException
     * @throws ConfigurationException
     */
    public abstract Iterator<UniversalPage> getConceptMap(LanguageSet ls) throws WikapidiaException, DaoException;

}
