package org.wikapidia.mapper;

import org.wikapidia.conf.ConfigurationException;
import org.wikapidia.core.WikapidiaException;
import org.wikapidia.core.dao.DaoException;
import org.wikapidia.core.dao.LocalLinkDao;
import org.wikapidia.core.dao.LocalPageDao;
import org.wikapidia.core.lang.LanguageSet;
import org.wikapidia.core.model.LocalPage;
import org.wikapidia.core.model.UniversalLink;
import org.wikapidia.core.model.UniversalPage;

import java.util.Iterator;

/**
 */
public abstract class ConceptMapper {

    /**
     * Algorithm IDs for the various concept parsing algorithms
     */
    public static final int MONOLINGUAL_ALGORITHM_ID = 0;
    public static final int CONCEPTUALIGN_ALGORITHM_ID = 1;

    private static int id;

    protected final LocalPageDao<LocalPage> localPageDao;

    /**
     * General purpose constructor for use by providers
     * @param localPageDao
     */
    public ConceptMapper(LocalPageDao<LocalPage> localPageDao) {
        this.localPageDao = localPageDao;
    }

    /**
     * Constructor for use by child algorithms to properly set the algorithm ID.
     * @param id
     * @param localPageDao
     */
    protected ConceptMapper(int id, LocalPageDao<LocalPage> localPageDao) {
        this(localPageDao);
        this.id = id;
    }

    public int getId() {
        return id;
    }

    /**
     * Returns an Iterator of UniversalPages generated by the concept mapping algorithm.
     * Requires a database of LocalPages.
     * @param ls the language set to map
     * @return an Iterator of universal pages
     * @throws DaoException
     * @throws ConfigurationException
     */
    public abstract Iterator<UniversalPage> getConceptMap(LanguageSet ls) throws WikapidiaException;

}
