CREATE TABLE IF NOT EXISTS LOCAL_LINK (
  LANG_ID SMALLINT NOT NULL,
  ANCHOR_TEXT TEXT NOT NULL,
  SOURCE_ID INT NOT NULL,
  DEST_ID INT NOT NULL,
  LOCATION INT NOT NULL,
  IS_PARSEABLE BOOLEAN NOT NULL,
  LOCATION_TYPE SMALLINT NOT NULL
)

