CREATE TABLE IF NOT EXISTS LOCAL_PAGE (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  LANG_ID SMALLINT NOT NULL,
  PAGE_ID INT NOT NULL,
  TITLE VARCHAR(257) NOT NULL,
  NAME_SPACE SMALLINT NOT NULL,
  IS_REDIRECT BOOLEAN NOT NULL,
  IS_DISAMBIG BOOLEAN NOT NULL
)

