CREATE TABLE IF NOT EXISTS META_INFO (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  COMPONENT VARCHAR(255) NOT NULL,
  LANG_ID SMALLINT,
  NUM_RECORDS INT NOT NULL DEFAULT 0,
  NUM_ERRORS INT NOT NULL DEFAULT 0,
  LAST_UPDATED TIMESTAMP,
  OTHER VARCHAR(65535) -- JSON FORMATTED DICTIONARY OF EXTRA INFO
)

