CREATE TABLE IF NOT EXISTS UNIVERSAL_LINK (
  LANG_ID SMALLINT NOT NULL,
  LOCAL_SOURCE_ID INT NOT NULL,
  LOCAL_DEST_ID INT NOT NULL,
  UNIV_SOURCE_ID INT NOT NULL,
  UNIV_DEST_ID INT NOT NULL,
  ALGORITHM_ID INT NOT NULL
)

