CREATE INDEX IF NOT EXISTS UNIVERSAL_PAGE_IDX_PAGE_ID ON UNIVERSAL_PAGE(UNIV_ID, ALGORITHM_ID);
CREATE INDEX IF NOT EXISTS UNIVERSAL_PAGE_IDX_PAGE_TYPE ON UNIVERSAL_PAGE(UNIV_ID, ALGORITHM_ID, NAME_SPACE)
