CREATE INDEX IF NOT EXISTS UNIVERSAL_LINK_IDX_SOURCE_ID ON UNIVERSAL_LINK(UNIV_SOURCE_ID, ALGORITHM_ID);
CREATE INDEX IF NOT EXISTS UNIVERSAL_LINK_IDX_DEST_ID ON UNIVERSAL_LINK(UNIV_DEST_ID, ALGORITHM_ID);
CREATE INDEX IF NOT EXISTS UNIVERSAL_LINK_IDX_BOTH_IDS ON UNIVERSAL_LINK(UNIV_SOURCE_ID, UNIV_DEST_ID, ALGORITHM_ID)
