DROP INDEX IF EXISTS WD_LABELS_IDX;
DROP INDEX IF EXISTS WD_DESC_IDX;
DROP INDEX IF EXISTS WD_ALIAS_IDX;
DROP INDEX IF EXISTS WD_STATEMENT_ENTITY_IDX;
DROP INDEX IF EXISTS WD_STATEMENT_VAL_IDX;
DROP INDEX IF EXISTS WD_STATEMENT_PROP_IDX
