CREATE INDEX IF NOT EXISTS WD_LABELS_IDX ON WIKIDATA_ENTITY_LABELS(ENTITY_TYPE, ENTITY_ID);
CREATE INDEX IF NOT EXISTS WD_DESC_IDX ON WIKIDATA_ENTITY_DESCRIPTIONS(ENTITY_TYPE, ENTITY_ID);
CREATE INDEX IF NOT EXISTS WD_ALIAS_IDX ON WIKIDATA_ENTITY_ALIASES(ENTITY_TYPE, ENTITY_ID);
CREATE INDEX IF NOT EXISTS WD_STATEMENT_ENTITY_IDX ON WIKIDATA_STATEMENT(ENTITY_TYPE, ENTITY_ID);
CREATE INDEX IF NOT EXISTS WD_STATEMENT_PROP_IDX ON WIKIDATA_STATEMENT(PROP_ID);
CREATE INDEX IF NOT EXISTS WD_STATEMENT_VAL_IDX ON WIKIDATA_STATEMENT(VAL_STR)
